name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        # 17 is the version supported by Minecraft 1.20.1
        # 21 is the newest version
        java: [17, 21]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout The Repository
      uses: actions/checkout@v4

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4
      
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Setup Gradle for optimal use
      uses: gradle/actions/setup-gradle@v4
      
    - name: Generate and submit dependency graph for GiHub vulnerabilities scanner
      uses: gradle/actions/dependency-submission@v4

    - name: Set Executable flag for Linux Permissions of Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Capture Linux Java 17 Build Artifacts
      if: ${{ matrix.java == '17' }}
      uses: actions/upload-artifact@v4
      with:
        name: enhanced-mason-trades-fabric-1.20.1
        path: build/libs/
